version: '3.4'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: paymentapi
      MYSQL_USER: paymentapi
      MYSQL_PASSWORD: paymentapi
    restart: on-failure
    ports:
      - "3306:3306"
