// GET all persons
GET http://localhost:8080/persons/
Accept: application/json

###

// GET all accounts
GET http://localhost:8080/accounts/
Accept: application/json

###

// GET one account
GET http://localhost:8080/accounts/9
Accept: application/json

###

// Create a new account
POST http://localhost:8080/accounts/
Content-Type: application/json

{
  "person": {
    "id": 1
  },
  "withdrawLimit": 100,
  "accountType": 1
}

###

// Deposit money in the account
POST http://localhost:8080/accounts/9/deposit
Content-Type: application/json

{
  "amount": 400
}

###

// GET all transactions
GET http://localhost:8080/accounts/9/transactions
Accept: application/json

###

// GET all transactions in a time interval
GET http://localhost:8080/accounts/9/transactions?startDate=2022-11-01&endDate=2022-11-04
Accept: application/json

###

// Withdraw money from the account
POST http://localhost:8080/accounts/9/withdraw
Content-Type: application/json

{
  "amount": 100
}
###

// Deactivate account
POST http://localhost:8080/accounts/9/deactivate
Content-Type: application/json

{}
###



